// <auto-generated />
namespace CommunityWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _250220189PM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_250220189PM));
        
        string IMigrationMetadata.Id
        {
            get { return "201802251431435_250220189PM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
